version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./public:/var/www/html/public
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:8.3-fpm
    volumes:
      - ./:/var/www/html

  db:
      image: postgres:latest
      restart: always
      ports:
          - '5432:5432'
      environment:
          POSTGRES_PASSWORD: password
      volumes:
          - ./dbdata:/var/lib/postgresql/data

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  kafka-ui:
      container_name: kafka-ui
      image: provectuslabs/kafka-ui:latest
      ports:
          - '8088:8080'
      environment:
          DYNAMIC_CONFIG_ENABLED: true
          KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:9092
      volumes:
          - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml
      depends_on:
          - kafka
